application: livestaats
version: stage
runtime: python
api_version: 1

handlers:

- url: /stylesheets
  static_dir: stylesheets

- url: /javascripts
  static_dir: javascripts

- url: /images
  static_dir: images

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: .*
  script: main.py
